// defaults
import '/imports/api/defaults/register.server';
// logs
import '/imports/api/logs/register.server';
// industries
import '/imports/api/industries/register.server';
// profiles
import '/imports/api/profiles/register.server';
// tokens
import '/imports/api/tokens/register.server';
// users
import '/imports/api/users/register.server';
// email
import '/imports/api/email/register.server';
// organizations
import '/imports/api/organizations/register.server';
// employees
import '/imports/api/employees/register.server';
// scheduler
import '/imports/api/scheduler/register.server';
// jobs
import '/imports/api/jobs/register.server';
// message_queue
import '/imports/api/message_queue/register.server';
// time
import '/imports/api/time/register.server';
// sending_plans
import '/imports/api/sending_plans/register.server';
// metrics
import '/imports/api/metrics/register.server';
// feedbacks
import '/imports/api/feedbacks/register.server';
// measures
import '/imports/api/measures/register.server';
// migration
import '/imports/api/migration/register.server';
// admin
import '/imports/api/admin/register.server';
// user messages
import '/imports/api/user_messages/register.server';
