Notification.TYPE = {
  FEEDBACK_CREATED: 'FEEDBACK_CREATED',
  FEEDBACK_UPDATED: 'FEEDBACK_UPDATED',
  FEEDBACK_REMOVED: 'FEEDBACK_REMOVED',
  EVALUATION_CREATED: 'EVALUATION_CREATED',
  EVALUATION_UPDATED: 'EVALUATION_UPDATED',
  EVALUATION_REMOVED: 'EVALUATION_REMOVED',
};
